(define (divisible? x y) (= (remainder x y) 0))
;(not (divisible? 3 2))
;(not (divisible? 4 2))
;(not (divisible? 5 2))
;(display "----")
(not (divisible? 4 3))
(not (divisible? 5 3))
(not (divisible? 6 3))
;(display "----")
;(not (divisible? 6 2))
;(not (divisible? 7 2))
;(not (divisible? 7 3))
;(not (divisible? 7 5))
